name: Create feature branch for issue

on:
  issues:
    types:
      - assigned

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: dev
      - name: Create feature branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b feature/${{ github.event.issue.number }}-${{ github.event.issue.title }}
          git push --set-upstream origin feature/${{ github.event.issue.name }}-${{ github.event.issue.title }}
