name: Create feature branch for issue

on:
  issues:
    types:
      - assigned
      - opened

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: dev
      - name: Create branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b issue-${{ github.event.issue.number }}
          git push --set-upstream origin issue-${{ github.event.issue.number }}